#!/usr/bin/env ruby
# frozen_string_literal: true

require "active_support/all"
require "bundler"
require "colorize"
require "optparse"
require "smt"

@input, @format = *Smt::Options.new.parse!

@format ||= Smt::DEFAULT_FORMAT

config = Smt::Config.load

time = if @input
  begin
    Time.parse(@input)
  rescue ArgumentError
    warn "Error: invalid time format '#{@input}'"
    exit 1
  end
else
  Time.current
end

return unless config

max_length = config.map { |entry| entry[:label].length }.max

config.each do |entry|
  Smt::Display.show(entry: entry, format: @format, max_length: max_length, time: time)
end
