#!/usr/bin/env ruby
# frozen_string_literal: true

require 'active_support/all'
require 'bundler'
require 'colorize'
require 'optparse'
require 'smt'

@input, @format = *Smt::Options.new.parse!

@format ||= Smt::DEFAULT_FORMAT

config = Smt::Config.load

time = if @input
         begin
           Time.parse(@input)
         rescue ArgumentError
           warn "Error: invalid time format '#{@input}'"
           exit 1
         end
       else
         Time.current
       end

return unless config

Smt::Display.table(entries: config, format: @format, time: time)
